const countries = [
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Andorre",
  "Angola",
  "Arabie Saoudite",
  "Argentine",
  "Arménie",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Belgique",
  "Bénin",
  "Bhoutan",
  "Biélorussie",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "Congo (Brazzaville)",
  "Congo (Kinshasa)",
  "Corée du Sud",
  "Costa Rica",
  "Côte d’Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Djibouti",
  "Égypte",
  "Émirats arabes unis",
  "Équateur",
  "Espagne",
  "Estonie",
  "États-Unis",
  "Éthiopie",
  "Finlande",
  "France",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Ghana",
  "Grèce",
  "Guinée",
  "Haïti",
  "Honduras",
  "Hongrie",
  "Inde",
  "Indonésie",
  "Irak",
  "Iran",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Japon",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Koweït",
  "Lettonie",
  "Liban",
  "Libéria",
  "Libye",
  "Lituanie",
  "Luxembourg",
  "Madagascar",
  "Malaisie",
  "Mali",
  "Malte",
  "Maroc",
  "Mauritanie",
  "Mexique",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Mozambique",
  "Namibie",
  "Népal",
  "Niger",
  "Nigéria",
  "Norvège",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palestine",
  "Panama",
  "Paraguay",
  "Pays-Bas",
  "Pérou",
  "Philippines",
  "Pologne",
  "Portugal",
  "Qatar",
  "République tchèque",
  "Roumanie",
  "Royaume-Uni",
  "Russie",
  "Rwanda",
  "Sénégal",
  "Serbie",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Sri Lanka",
  "Suède",
  "Suisse",
  "Syrie",
  "Tadjikistan",
  "Tanzanie",
  "Tchad",
  "Thaïlande",
  "Tunisie",
  "Turquie",
  "Ukraine",
  "Uruguay",
  "Venezuela",
  "Vietnam",
  "Yémen",
  "Zambie",
  "Zimbabwe"
];

export default countries;
