export const SET_DEVIS_DATA = 'SET_DEVIS_DATA'
export const RESET_DEVIS_DATA = 'RESET_DEVIS_DATA'
export const DEVIS_SUBMIT_REQUEST = 'DEVIS_SUBMIT_REQUEST';
export const DEVIS_SUBMIT_SUCCESS = 'DEVIS_SUBMIT_SUCCESS';
export const DEVIS_SUBMIT_FAIL = 'DEVIS_SUBMIT_FAIL';  
export const DEVIS_LIST_MY_REQUEST = 'DEVIS_LIST_MY_REQUEST';
export const DEVIS_LIST_MY_SUCCESS = 'DEVIS_LIST_MY_SUCCESS';
export const DEVIS_LIST_MY_FAIL = 'DEVIS_LIST_MY_FAIL';
export const DEVIS_DETAILS_FAIL = 'DEVIS_DETAILS_FAIL';
export const DEVIS_DETAILS_SUCCESS = 'DEVIS_DETAILS_SUCCESS';
export const DEVIS_DETAILS_REQUEST = 'DEVIS_DETAILS_REQUEST';
 export const DEVIS_LIST_ADMIN_REQUEST = 'DEVIS_LIST_ADMIN_REQUEST';
export const DEVIS_LIST_ADMIN_SUCCESS = 'DEVIS_LIST_ADMIN_SUCCESS';
export const DEVIS_LIST_ADMIN_FAIL = 'DEVIS_LIST_ADMIN_FAIL';

  
export const DEVIS_DELETE_REQUEST = 'DEVIS_DELETE_REQUEST'
export const DEVIS_DELETE_SUCCESS = 'DEVIS_DELETE_SUCCESS'
export const DEVIS_DELETE_FAIL = 'DEVIS_DELETE_FAIL'

export const DEVIS_UPDATE_STATUS_REQUEST = 'DEVIS_UPDATE_STATUS_REQUEST'
export const DEVIS_UPDATE_STATUS_SUCCESS = 'DEVIS_UPDATE_STATUS_SUCCESS'
export const DEVIS_UPDATE_STATUS_FAIL = 'DEVIS_UPDATE_STATUS_FAIL'
  
  