export const SHIPMENTS_LIST_REQUEST = 'SHIPMENTS_LIST_REQUEST'
export const SHIPMENTS_LIST_SUCCESS = 'SHIPMENTS_LIST_SUCCESS'
export const SHIPMENTS_LIST_FAIL = 'SHIPMENTS_LIST_FAIL'

export const SHIPMENT_ADD_REQUEST = 'SHIPMENT_ADD_REQUEST'
export const SHIPMENT_ADD_SUCCESS = 'SHIPMENT_ADD_SUCCESS'
export const SHIPMENT_ADD_FAIL = 'SHIPMENT_ADD_FAIL'